# arguments for dataset
dataset: bogota
nclass: 2
crop_size: 448
aug: True
data_root: /media/llog/AGMM-SASSdata/Bogota
mode: 'scribble'

# arguments for training
epochs: 80
batch_size: 1
lr: 0.001  # 4GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 2
conf_thresh: 0.95

# arguments for model
aux: False
backbone: DINOV2b            #DINOV2b(s/b/l/g) reins_dinov2b(s/b/l/g)
# attn choice: CA or CBAM or SA. (default attn1:CA, attn2:CBAM)
attn1: CA
attn2: CBAM
