# arguments for dataset
dataset: vaihingen
nclass: 5
crop_size: 322
aug: True
data_root: /media/llog/Mydata/publicdata/Vaihingen/
mode: 'polygon'   #label type(line,point,polygon,full)
sup_id: 'an11'          #label type(an11,an22,an33,an44)

# arguments for training
epochs: 80
batch_size: 2
lr: 0.001  # 4GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 5
conf_thresh: 0.95

# arguments for model
aux: False
backbone: DINOV2b
# attn choice: CA or CBAM or SA. (default attn1:CA, attn2:CBAM)
attn1: CA
attn2: CBAM